stages:
  - test
  - build
  - cleanup

env_test:
  stage: test
  script:
    - echo "DOCKER_HOST=$DOCKER_HOST"
    - docker info


docker_build_and_push:
  stage: build
  resource_group: docker_pipeline_lock
  only:
    - master
  tags:
    - linux
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

cleanup_docker_artifacts:
  stage: cleanup
  resource_group: docker_pipeline_lock
  only:
    - master
  tags:
    - linux
  needs:
    - docker_build_and_push
  script:
    - echo "Dangling Images (werden gelöscht):"
    - docker images -f "dangling=true"
    - docker image prune -f
    - docker builder prune -f
