stages:
  - build

build:
  stage: build
  tags:
    - linux
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}:latest" .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}:latest"
