before_script:
  - set -x  # aktiviert Debug-Ausgabe
  - env | grep CI_  # zeigt alle CI-Variablen

stages:
  - build

build_image:
  stage: build
  only:
    - master
  tags:
    - linux
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

