name: CI
run-name: ${{ github.actor }} pushed Something. Updating Deployment
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    env:
      REPO_URL: ${{ github.server_url }}/${{ github.repository }}
    steps:
      - name: Add /usr/local/bin to PATH
        run: echo "/usr/local/bin" >> $GITHUB_PATH
    
      - name: Stop server
        run: pm2 delete website || echo "Not running"

      - name: Remove old version
        run: |
          cd $LOCAL_REPO_PATH
          rm -rf ${{ github.event.repository.name }}
        
      - name: Checkout repository
        run: |
          cd $LOCAL_REPO_PATH
          git clone $REPO_URL

      - name: Install dependencies
        run: |
          cd $LOCAL_REPO_PATH/${{ github.event.repository.name }}
          npm i
        
      - name: Build the project
        run: |
          cd $LOCAL_REPO_PATH/${{ github.event.repository.name }}
          npm run build
        
      - name: Deploy
        run: |
          cd $LOCAL_REPO_PATH/${{ github.event.repository.name }}  
          pm2 start "npm run start" --name website
          pm2 save
